name: Java CI with Maven

on:
  push:
    branches: ["main", "dev", "prod_support"]
  pull_request:
    branches: [ "main", "dev", "prod-support" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 22
        uses: actions/setup-java@v1.0
        with:
          java-version: 22
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven verify
        run: mvn -B clean verify